paper_len: 10.0
abs_lead_step: 10
format_4_by_3: [["I", "II", "III"], ["aVR", "aVL", "aVF", "AVR", "AVL", "AVF"], ["V1", "V2", "V3"], ["V4", "V5", "V6"]]
leadNames_12: ["III", 'aVF', 'V3', 'V6', 'II', 'aVL', 'V2', 'V5', 'I', 'aVR', 'V1', 'V4']
format_2_by_6: [["I", "II", "III","aVR", "aVL", "aVF", "AVR", "AVL", "AVF"], ["V1", "V2", "V3","V4", "V5", "V6"]]
#start_plot_xy_delta_dict: {"III": [None, None], 'aVF':[None, None], 'V3':[None, None], 'V6':[None, None], 'II':[None, None], 'aVL':[None, None], 'V2':[None, None], 'V5':[None, None], 'I':[None, None], 'aVR':[None, None], 'V1':[None, None], 'V4':[None, None]}
#start_plot_xy_delta_from_json: True
#sample_rate: 100 #int
#rec_file_name:  #str
#output_dir: #str
#full_mode: None # None or lead name
#store_text_bbox:
#papersize:  #A0, A1, A2, A3, A4 or letter
#show_grid: True #bool
#show_dc_pulse: True #bool
#show_dc_pulse: True #bool
